# CI/CD cho DateTimeChecker
name: CI/CD for DateTimeChecker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:  # Thêm quyền cho GITHUB_TOKEN
      checks: write
      pull-requests: write

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Build and Test with Maven
        run: mvn clean test

      - name: Generate JUnit Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'target/surefire-reports/*.xml'

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: target/surefire-reports/

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Test Report
          path: target/surefire-reports/*.xml
          reporter: java-junit
